# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.3.2"

default_platform :ios


platform :ios do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"

    cocoapods

    increment_build_number

    gym(scheme: "TimeCurl Bots", use_legacy_build_api: true) # Build your app - more options available

    #does not work
    #xctest(scheme: "TimeCurl Bots", workspace: "TimeCurl.xcworkspace", destination: "name=iPhone 5s,OS=9.0")
  end

  desc "Test lane"
  lane :test do
    slack(
      message: "Successfully uploaded testflight build"
    )
  end

  desc "Takes the screenshots"
  lane :create_screenshots do
    snapshot
    frameit
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    sigh
    pilot(
      changelog: "some changelog message"
    )
    slack(
      message: "Successfully uploaded testflight build"
    )
  end

  desc "Deploy a new version to the App Store"
  desc "** Full Markdown** Support: `code`"
  lane :metadata do
    deliver(skip_deploy: true, force: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
  end


  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

end


# More information about multiple platforms in fastlane: 
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
